### ISSUE TITLE
Support on Huggingface transformers

### ISSUE THREAD

**Issue by ImKeTT** [google/JetStream#44]
Hi, great work! Do you have any future plans on supporting the Flax/Jax implemented Huggingface transformer models?

**Comment by vipannalla** [comment]
JetStream is agnostic to particular model frameworks and should work for all LLM models if the engine supports it. Currently, we have two reference engine implementations -- one for [JAX](https://github.com/google/JetStream/blob/main/docs/online-inference-with-maxtext-engine.md) models and one for [Pytorch](https://github.com/google/jetstream-pytorch/blob/main/README.md) models. 

Can you try/check if your model is supported in Maxtext repo?

**Comment by ImKeTT** [comment]
Thanks for your reply, seems that we might need a lot more efforts if we want to use LLMs that are currently not supported in Maxtext.
