### ISSUE TITLE
Support I/O with text and token ids

### ISSUE THREAD

**Issue by JoeZijunZhou** [google/JetStream#79]
- Customer request: We use multiple languages for clients and cannot implement detokenization in each one. Need to have server-side detokenization support.

**Comment by kiratp** [comment]
Just chiming in here that the customer quoted is us :). The main challenger is that we have clients in multiple languages that don’t always have tokenizer implementations readily available. Every other prominent model server does detokenization, hence the request. 

Doesn’t hurt that there are so many CPU cores on the TPU VMs that are mostly idle during inference anyway. 

Thanks @JoeZijunZhou !

**Comment by JoeZijunZhou** [comment]
Resolved this issue in #78 . It's available in main.
